spring:
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 20
  cloud:
    aws:
      s3:
        bucket: capstone-image-s3
        path:
          items: items      # 상품 이미지가 저장되는 경로
          item_previews: item_previews  # 상품의 미리보기 이미지가 저장되는 경로
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
  profiles:
    active: ${ACTIVE_PROFILE}
  jackson:
    time-zone: Asia/Seoul
com:
  example:
    jwt:




