spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/capstoneDB
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: Info

log:
  config:
    path: /Users/seongsiyeong/Desktop/log
    filename: text