spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/capstoneDB
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: Info

log:
  config:
    path: /var/customlog
    filename: custom